monday:
  - start: '08:20'
    stop:  '09:00'
  - start: '09:50'
    stop:  '10:00'
  - start: '11:20'
    stop:  '11:30'
  - start: '12:50'
    stop:  '13:00'
  - start: '14:20'
    stop:  '14:30'
  - start: '15:50'
    stop:  '16:00'
  - start: '16:50'
    stop:  '17:00'
  - start: '17:20'
    stop:  '17:30'
  - start: '18:50'
    stop:  '19:00'
  - start: '20:20'
    stop:  '20:30'
  - start: '21:08'
    stop:  '22:00'
tuesday:
  - start: '08:20'
    stop:  '09:00'
  - start: '09:50'
    stop:  '10:00'
  - start: '11:20'
    stop:  '11:30'
  - start: '12:50'
    stop:  '13:00'
  - start: '14:20'
    stop:  '14:30'
  - start: '15:50'
    stop:  '16:00'
  - start: '17:20'
    stop:  '17:30'
  - start: '18:50'
    stop:  '19:00'
  - start: '20:20'
    stop:  '20:30'
  - start: '21:50'
    stop:  '22:00'
  - start: '21:20'
    stop:  '21:30'
  - start: '21:50'
    stop:  '22:00'
  - start: '22:20'
    stop:  '22:30'
  - start: '22:50'
    stop:  '23:00'
  - start: '23:20'
    stop:  '23:30'
  - start: '23:50'
    stop:  '00:00'
  - start: '00:20'
    stop:  '00:30'
  - start: '00:50'
    stop:  '01:00'
wednesday:
  - start: '08:20'
    stop:  '09:00'
  - start: '09:50'
    stop:  '10:00'
  - start: '11:20'
    stop:  '11:30'
  - start: '12:50'
    stop:  '13:00'
  - start: '14:20'
    stop:  '14:30'
  - start: '15:50'
    stop:  '16:00'
  - start: '17:20'
    stop:  '17:30'
  - start: '18:50'
    stop:  '19:00'
  - start: '20:20'
    stop:  '20:30'
  - start: '21:50'
    stop:  '22:00'
thursday:
  - start: '08:20'
    stop:  '09:00'
  - start: '09:50'
    stop:  '10:00'
  - start: '11:20'
    stop:  '11:30'
  - start: '12:50'
    stop:  '13:00'
  - start: '14:20'
    stop:  '14:30'
  - start: '15:50'
    stop:  '16:00'
  - start: '17:20'
    stop:  '17:30'
  - start: '18:50'
    stop:  '19:00'
  - start: '20:20'
    stop:  '20:30'
  - start: '21:50'
    stop:  '22:00'
friday:
  - start: '08:20'
    stop:  '09:00'
  - start: '09:50'
    stop:  '10:00'
  - start: '11:20'
    stop:  '11:30'
  - start: '12:50'
    stop:  '13:00'
  - start: '14:20'
    stop:  '14:30'
  - start: '15:50'
    stop:  '16:00'
  - start: '17:20'
    stop:  '17:30'
  - start: '18:50'
    stop:  '19:00'
  - start: '20:20'
    stop:  '20:30'
  - start: '21:50'
    stop:  '22:00'
saturday:
  - start: '18:30'
    stop:  '22:45'
sunday:
  - start: '19:40'
    stop:  '19:50'
  - start: '19:51'
    stop:  '19:55'
  - start: '21:49'
    stop:  '21:55'
